name: Generate Index

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate index.html
        run: node scripts/generate-index.js

      - name: Commit generated file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add index.html

          git diff --cached --quiet || git commit -m "auto generate index"

          git push
